# SITE CONFIGURATION
baseurl: "/"
url: "https://paymentshield.tech"
title: Paymentshield Tech # site's title
description: "The technical blog of Paymentshield" # used by search engines

permalink: /:year/:month/:day/:title

defaults:
  - scope:
      path: "" # an empty string here means all necessary files are in the project
    values:
      image: assets/img/headers/header-back.jpg

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  avatar: assets/img/psl-logo.png
  color_image: /assets/img/lineart.png # In post when you set color
  favicon: assets/favicon.ico

  # Header and footer text
  header_text: The techniques, the technology, and the team that build the shield at Paymentshield
  header_feature_image: assets/img/headers/header-back.jpg
  footer_text: >
    Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>

  # Blog
  excerpt: true # Or "truncate" (first 250 characters), "false" to disable

  # Icons
  rss: true  # Make sure you created a feed.xml with feed.xml layout
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: "Paymentshield"
  instagram:
  keybase:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_overflow:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "PslTech" # "twitter username"
  vimeo:
  wordpress:
  youtube:

  # Sharing options
  share_buttons:
    facebook: true
    twitter: true
    tumblr:
    pinterest:
    pocket:
    reddit: true
    linkedin: true
    wordpress:
    email: true

  # Scripts / Features 
  google_analytics: UA-154127007-1 # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: false # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_share_on: "Share on"
  str_add_to: "Add to"
  str_email: "Email"
  str_tweet: "Tweet"
  str_pin_it: "Pin it"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Post navigation
  post_navigation: true

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# AUTHORS
authors:
  sg: # author-id
    name: Ste Griffiths
    avatar: "assets/img/avatars/ste.jpg"
    # url: ""
  tp:
    name: Toria Pardoe
    avatar: "assets/img/avatars/toria.jpg"
  sm:
    name: Sacha Mitchell
    avatar: "assets/img/avatars/anon.jpg"
  ts:
    name: Tim Stalker
    avatar: "assets/img/avatars/anon.jpg"
  sh:
    name: Sarah Handford
    avatar: "assets/img/avatars/sarah.jpg"
  nc:
    name: Nick Cowling
    avatar: "assets/img/avatars/nick.jpg"

# PORTFOLIO
# collections:
  # portfolio:
    # output: true
    # permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", "Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", ".idea", "vendor/*",
          "LICENSE", "README.md", "screenshot.png", "assets/package.json", "assets/node_modules", "assets/gulpfile.js"]

# theme: type-on-strap # Uncomment if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap # If using as a remote_theme in github
